config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get '/watch/:id', to: 'users#watch', as: :watch
  get '/stream', to: 'users#stream', as: :stream

  root 'users#stream'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/stream.rb
class Stream < ApplicationRecord
  before_create do |stream|
    session = OpenTokClient.create_session
    stream.tokbox_session_id = session.session_id
  end

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    
  has_one :stream
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/streams_controller.rb
class StreamsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
  
    def stream
      @stream     = current_user.stream || current_user.create_stream
      gon.opentok = opentok_data(@stream)
    end
  
    def watch
      @stream = User.find(params[:id]).stream
      gon.opentok = opentok_data(@stream)
    end
  
    private
  
    def opentok_data(stream)
        token = OpenTokClient.generate_token(stream.tokbox_session_id)
        { sessionId: stream.tokbox_session_id, apiKey: Rails.application.credentials.tokbox[:opentok_key], token: token }
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/streams_helper.rb
module StreamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LiveStreaming</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= Gon::Base.render_data %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/stream.html.erb
<%= javascript_include_tag "//static.opentok.com/webrtc/v2.2/js/TB.min.js" %>
<h1>Your stream</h1>
<div id="publisher"></div>
Link to your stream: <%= link_to watch_url(@stream.user.id), watch_url(@stream.user.id) %>

app/views/users/watch.html.erb
<%= javascript_include_tag "//static.opentok.com/webrtc/v2.2/js/TB.min.js" %>
<h1><%= @stream.user.email %>'s stream</h1>
<div id="stream"></div>